import { BookOpen } from "lucide-react";
import { brand } from "@/lib/content";
import { pageMetadata } from "@/lib/site";
import { FinalCTA } from "@/components/final-cta";
import { Container, Eyebrow } from "@/components/ui";

export const metadata = pageMetadata("About Bayzicks", "Bayzicks makes digital careers easier to understand for beginners through clear explanations, practical resources and useful first steps.", "/about");

export default function AboutPage() {
  return <main id="main-content"><Container><div className="page-intro"><Eyebrow>THE IDEA BEHIND BAYZICKS</Eyebrow><h1>The digital world,<br />a little easier to understand.</h1><p>{brand.purpose}</p></div><section className="about-mission" aria-labelledby="about-purpose-title"><div className="about-mission-copy"><h2 id="about-purpose-title">A useful explanation can<br />be a good beginning.</h2><p>There’s plenty of information about digital work online. What’s often missing is the context: what a role involves, why a skill matters and which part to learn first.</p><p>Bayzicks brings those pieces together. The focus is on explaining roles, skills, tools, learning paths and opportunities in language that makes sense when you’re new to all of it.</p><p>The resources are here to help you explore and make informed choices. They aren’t a promise of a job, a particular income or an overnight career change.</p></div><div className="founder-placeholder"><BookOpen size={50} strokeWidth={1.1} aria-hidden="true" /><h2>More of the story, soon.</h2><p>This space will introduce the person behind Bayzicks, in their own words.</p>{/* Replace this complete block with the approved founder photo, biography and experience. Do not invent personal credentials or use a stock founder photo. */}</div></section><section className="about-values page-section" aria-label="How Bayzicks approaches learning"><article className="about-value"><span>01</span><h2>Explain the work.</h2><p>Go beyond a job title and understand what someone actually does during their working day.</p></article><article className="about-value"><span>02</span><h2>Keep it practical.</h2><p>Connect an explanation to something you can try, practise or use to plan your next step.</p></article><article className="about-value"><span>03</span><h2>Start with the beginner.</h2><p>Explain unfamiliar language and build on the basics instead of assuming you already know them.</p></article></section></Container><FinalCTA /></main>;
}
