import { ImageResponse } from "next/og";

export const alt = "Bayzicks. The digital world, made simple. A starting point for digital careers.";
export const size = { width: 1200, height: 630 };
export const contentType = "image/png";

export default function OpenGraphImage() {
  return new ImageResponse(<div style={{ width: "100%", height: "100%", display: "flex", flexDirection: "column", background: "#f7f5ed", color: "#193c32", padding: "54px 70px", position: "relative" }}><div style={{ display: "flex", fontSize: 47, letterSpacing: "-2px" }}>bayzicks<span style={{ color: "#b16a41", marginLeft: 7 }}>✳</span></div><div style={{ display: "flex", marginTop: 63, fontSize: 77, fontWeight: 400, lineHeight: 1.08, letterSpacing: "-3px", maxWidth: 800 }}>The digital world,<br />made simple.</div><div style={{ display: "flex", marginTop: 34, fontSize: 23, color: "#677167" }}>Digital careers, starting with the basics.</div><div style={{ position: "absolute", right: 74, top: 74, width: 192, height: 482, display: "flex", flexDirection: "column", justifyContent: "space-between", borderLeft: "1px solid #cbd2bf", paddingLeft: 35 }}><div style={{ display: "flex", flexDirection: "column", gap: 9, fontSize: 20 }}><span style={{ color: "#b16a41", fontSize: 14 }}>01</span>Roles</div><div style={{ display: "flex", flexDirection: "column", gap: 9, fontSize: 20 }}><span style={{ color: "#b16a41", fontSize: 14 }}>02</span>Skills</div><div style={{ display: "flex", flexDirection: "column", gap: 9, fontSize: 20 }}><span style={{ color: "#b16a41", fontSize: 14 }}>03</span>Tools</div><div style={{ display: "flex", flexDirection: "column", gap: 9, fontSize: 20 }}><span style={{ color: "#b16a41", fontSize: 14 }}>04</span>Learning paths</div><div style={{ display: "flex", flexDirection: "column", gap: 9, fontSize: 20 }}><span style={{ color: "#b16a41", fontSize: 14 }}>05</span>Opportunities</div></div><div style={{ display: "flex", marginTop: "auto", fontSize: 12, letterSpacing: "2px", color: "#677167" }}>YOUR DIGITAL CAREER STARTS WITH THE BASICS.</div></div>, size);
}
