import Link from "next/link";
import { pageMetadata } from "@/lib/site";
import { Container, Eyebrow } from "@/components/ui";

export const metadata = pageMetadata("Privacy Policy", "How Bayzicks forms handle newsletter requests and enquiries, including email-service providers, consent and your privacy choices.", "/privacy");

// LEGAL REVIEW REQUIRED: add the legal controller's registered name/address,
// privacy contact, actual hosting provider, lawful bases by jurisdiction, retention
// periods, international-transfer safeguards and any analytics/cookie details.
// Have this policy reviewed against the real operation before public launch.
export default function PrivacyPage() {
  return <main id="main-content"><Container className="legal-page"><Eyebrow>YOUR INFORMATION</Eyebrow><h1>Privacy Policy</h1><p className="legal-date">Starter policy · legal and business review required before launch</p><aside className="legal-notice">This is a starter policy, not a final legal notice. Bayzicks’ legal business identity, privacy contact details, retention schedule and jurisdiction-specific requirements still need to be added and reviewed before public launch.</aside><div className="legal-prose">
    <h2>1. What this policy covers</h2><p>This page explains how the Bayzicks website is designed to handle personal information submitted through its newsletter, contact and collaboration forms. The final business responsible for this information must be identified here before launch.</p>
    <h2>2. Information you choose to share</h2><p>A guide request asks for your email address. When the service is live, that address is added to the configured Mailchimp audience together with tags identifying the requested resource, signup source and consent wording version.</p><p>Contact and collaboration forms ask for your name, email, enquiry category and message. A collaboration enquiry can also include an organisation name. These forms are separate from newsletter signup and do not automatically subscribe you to marketing emails.</p>
    <h2>3. How the information is used</h2><ul><li>To send a requested resource and, with your consent, occasional Bayzicks emails.</li><li>To respond to a contact or collaboration enquiry.</li><li>To protect the forms from misuse and keep the website working.</li></ul><p>The form labels and consent text explain the intended use when you submit. Any additional uses and their applicable lawful bases must be reviewed and disclosed before they are introduced.</p>
    <h2>4. Email and hosting providers</h2><p>The live newsletter integration uses Mailchimp to manage the audience and send emails. The configured enquiry integration uses Resend to forward messages to Bayzicks. These providers receive the information needed to perform the relevant service. Website hosting may also process standard technical request information.</p><p>The final hosting provider, provider agreements, processing locations and any required international-transfer safeguards must be confirmed before launch.</p>
    <h2>5. Preview mode</h2><p>When a form displays a preview-mode notice, the application validates the submission but does not add the email to Mailchimp, send a message to Bayzicks or save the submitted form contents in a database. Preview responses explicitly say that no email or submission has been sent. Normal hosting request logs may still be generated.</p>
    <h2>6. Technical information and cookies</h2><p>The application uses a temporary, in-memory request limiter to protect forms. It stores a hashed request identifier rather than the submitted message. Hosting infrastructure may process IP addresses and technical logs. The application does not include advertising pixels, analytics scripts or tracking cookies by default.</p><p>If analytics, embedded content, additional spam-protection services or other tracking are added, update this policy and review whether a cookie-consent mechanism is required.</p>
    <h2>7. Unsubscribing and your choices</h2><p>Live Bayzicks marketing emails must include Mailchimp’s unsubscribe link. You can use it to stop future marketing emails. The integration does not silently resubscribe addresses that have opted out.</p><p>Depending on the laws that apply, you may have rights to access, correct, delete or restrict use of your personal information. You can <Link href="/contact">contact Bayzicks</Link> about a privacy question. A direct privacy contact and any required complaint or supervisory-authority details must be added before launch.</p>
    <h2>8. Retention and security</h2><p>Personal information should be kept only for as long as needed for the stated purpose and applicable obligations. Bayzicks’ actual retention and deletion schedule must be added here before launch. Mailchimp and Resend credentials are used only on the server and are not sent to visitors’ browsers.</p>
    <h2>9. Changes to this policy</h2><p>This policy should be updated when the website’s services or data practices change. A reviewed publication date and subsequent update dates should be shown with the final policy.</p>
  </div></Container></main>;
}
